# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve the penalized logistic regression.
#' @param y samples of binary outcome which is a \eqn{n*1} vector.
#' @param x samples of covariates which is a \eqn{n*p} matrix.
#' @param off offset in logistic regression.
#' @param pen 1: MCP estimator; 2: SCAD estimator.
#' @param lam value of the lasso penalty parameter \eqn{\lambda} for \eqn{\beta_1} and \eqn{\beta_2}.
#' @param beta initial estimates.
#' @return A numeric vector, estimate of beta
#' @export 
penC <- function(x, y, off, beta, lam, pen) {
    .Call('_CSTE_penC', PACKAGE = 'CSTE', x, y, off, beta, lam, pen)
}

